/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

import {getFiles, filterDirectory} from "./scripts/automation/helpers/util.mjs";

const sidebars = {};

const modules = getFiles(process.cwd() + "/docs", filterDirectory, false);

for ( const module of modules) {
  sidebars[module] = [{ type: "autogenerated", dirName: module }];
}

module.exports = sidebars;
